# Generated by Django 5.1.1 on 2024-10-03 23:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('deliverer_name', models.CharField(max_length=255)),
                ('deliverer_id', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_id', models.CharField(max_length=50)),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='dispatch_files/')),
                ('quantity_dispatched', models.PositiveIntegerField(default=0)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('actual_transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.beneficiary')),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_date', models.DateField()),
                ('document_number', models.CharField(max_length=50)),
                ('supply_receipt_number', models.CharField(max_length=50)),
                ('delivered_by_name', models.CharField(max_length=100)),
                ('delivered_by_id', models.CharField(max_length=50)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('imported_quantity', models.PositiveIntegerField(default=0)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.station')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_quantity', models.PositiveIntegerField()),
                ('expected_return_date', models.DateField()),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnReceiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('receiving_date', models.DateField(editable=False)),
                ('document_number', models.CharField(max_length=50)),
                ('delivered_by_name', models.CharField(max_length=100)),
                ('delivered_by_id', models.CharField(max_length=50)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('items', models.ManyToManyField(through='Transactions.ReturnItem', to='Enventory.item')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='Transactions.receiving')),
                ('station', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.station')),
                ('supplier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.supplier')),
                ('warehouse', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='returnitem',
            name='return_receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.returnreceiving'),
        ),
    ]
