# Generated by Django 5.1.1 on 2024-09-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_date', models.DateField()),
                ('document_number', models.CharField(max_length=50)),
                ('supply_receipt_number', models.CharField(max_length=50)),
                ('delivered_by_name', models.CharField(max_length=100)),
                ('delivered_by_id', models.CharField(max_length=50)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.station')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_quantity', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_items', to='Transactions.receiving')),
            ],
        ),
    ]
