# Generated by Django 5.1.1 on 2024-10-13 20:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_date', models.DateField(default=django.utils.timezone.now)),
                ('document_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('delivered_by_name', models.CharField(max_length=100)),
                ('delivered_by_id', models.CharField(max_length=50)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='damage_attachments/')),
                ('damaged_quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('document_number', models.CharField(default=1, max_length=50)),
                ('deliverer_name', models.CharField(max_length=255)),
                ('deliverer_id', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_id', models.CharField(max_length=50)),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='dispatch_files/')),
                ('quantity_dispatched', models.PositiveIntegerField(default=0)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('actual_transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.beneficiary')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('dispatch_date', models.DateField(editable=False)),
                ('document_number', models.CharField(max_length=50)),
                ('delivered_by_name', models.CharField(max_length=100)),
                ('delivered_by_id', models.CharField(max_length=50)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='return_attachments/')),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('expected_return_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('actual_return_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.beneficiary')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.dispatch')),
                ('item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('warehouse', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_date', models.DateField()),
                ('document_number', models.CharField(max_length=50)),
                ('supply_receipt_number', models.CharField(max_length=50)),
                ('delivered_by_name', models.CharField(max_length=100)),
                ('delivered_by_id', models.CharField(max_length=50)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('imported_quantity', models.PositiveIntegerField(default=0)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.station')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('document_number', models.CharField(max_length=50)),
                ('delivered_by_name', models.CharField(max_length=100)),
                ('delivered_by_id', models.CharField(max_length=50)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='return_attachments/')),
                ('receiving_date', models.DateField(editable=False)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.receiving')),
                ('station', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.station')),
                ('supplier', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.supplier')),
                ('warehouse', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
            options={
                'verbose_name': 'Receiving Return',
                'verbose_name_plural': 'Receiving Returns',
            },
        ),
        migrations.CreateModel(
            name='TransferOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('paper_number', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_job_number', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_job_number', models.CharField(max_length=50)),
                ('statement', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='Enventory.warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_transferred', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('transfer_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='Transactions.transferoperation')),
            ],
        ),
    ]
