# Generated by Django 5.1.1 on 2024-10-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_item_warehouse'),
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiving',
            name='item',
        ),
        migrations.AddField(
            model_name='receiving',
            name='stock_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
    ]
