# Generated by Django 5.1.1 on 2024-09-27 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='imported_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receiving',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='item_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ImportedItem',
        ),
    ]
