# Generated by Django 5.1.1 on 2024-09-27 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
        ('Transactions', '0002_receiving_imported_quantity_receiving_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField()),
                ('deliverer_name', models.CharField(max_length=255)),
                ('deliverer_id', models.CharField(max_length=50)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='dispatch_files/')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.beneficiary')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispatched', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_date', models.DateField()),
                ('actual_transfer_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_items', to='Transactions.dispatch')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem')),
            ],
        ),
    ]
