# Generated by Django 5.1.1 on 2024-10-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_remove_receiving_item_receiving_stock_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
