# Generated by Django 5.1.1 on 2024-10-04 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
        ('Transactions', '0002_returnitem_actual_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnreceiving',
            name='items',
        ),
        migrations.RemoveField(
            model_name='returnreceiving',
            name='receiving',
        ),
        migrations.RemoveField(
            model_name='returnreceiving',
            name='station',
        ),
        migrations.RemoveField(
            model_name='returnreceiving',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='returnreceiving',
            name='warehouse',
        ),
        migrations.CreateModel(
            name='ReceivingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('document_number', models.CharField(max_length=50)),
                ('returned_by_name', models.CharField(max_length=100)),
                ('returned_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/returns/')),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='Transactions.receiving')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.station')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='ReturnItem',
        ),
        migrations.DeleteModel(
            name='ReturnReceiving',
        ),
    ]
