# Generated by Django 5.1.1 on 2024-10-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0010_remove_station_warehouse'),
        ('Transactions', '0003_alter_receiving_document_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='item',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='stock_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
    ]
