# Generated by Django 5.1.1 on 2024-10-04 04:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
        ('Transactions', '0003_remove_returnreceiving_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivingreturn',
            name='returned_by_id',
        ),
        migrations.RemoveField(
            model_name='receivingreturn',
            name='returned_by_name',
        ),
        migrations.AddField(
            model_name='receivingreturn',
            name='actual_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingreturn',
            name='delivered_by_id',
            field=models.CharField(default='unknown_id', max_length=50),
        ),
        migrations.AddField(
            model_name='receivingreturn',
            name='delivered_by_name',
            field=models.CharField(default='Unknown Deliverer', max_length=100),
        ),
        migrations.AddField(
            model_name='receivingreturn',
            name='expected_response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingreturn',
            name='received_by_id',
            field=models.CharField(default='unknown_id', max_length=50),
        ),
        migrations.AddField(
            model_name='receivingreturn',
            name='received_by_name',
            field=models.CharField(default='Unknown Deliverer', max_length=100),
        ),
        migrations.AddField(
            model_name='receivingreturn',
            name='receiving_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='receivingreturn',
            name='warehouse',
            field=models.ForeignKey(default=21, editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='item',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='Transactions.receiving', verbose_name='Receiving'),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='station',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.station'),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='supplier',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Enventory.supplier'),
        ),
    ]
