# Generated by Django 5.1.1 on 2024-09-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
        ('Transactions', '0003_dispatch_dispatcheditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatcheditem',
            name='stock_item',
        ),
        migrations.AddField(
            model_name='dispatcheditem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
    ]
