# Generated by Django 5.1.1 on 2024-10-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
        ('Transactions', '0004_remove_receivingreturn_returned_by_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receivingreturn',
            options={'verbose_name': 'Receiving Return', 'verbose_name_plural': 'Receiving Returns'},
        ),
        migrations.RenameField(
            model_name='receivingreturn',
            old_name='actual_response_date',
            new_name='actual_return_date',
        ),
        migrations.RenameField(
            model_name='receivingreturn',
            old_name='expected_response_date',
            new_name='expected_return_date',
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='return_attachments/'),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='delivered_by_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='delivered_by_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='received_by_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='received_by_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='receiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transactions.receiving'),
        ),
        migrations.AlterField(
            model_name='receivingreturn',
            name='receiving_date',
            field=models.DateField(editable=False),
        ),
    ]
