# Generated by Django 5.1.1 on 2024-10-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0011_beneficiary_item_item_warehouse_station_item_and_more'),
        ('Transactions', '0004_remove_dispatch_item_dispatch_stock_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='receiving',
            name='stock_item',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AddField(
            model_name='receiving',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='document_number',
            field=models.CharField(max_length=50),
        ),
    ]
