# Generated by Django 5.1.1 on 2024-10-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0006_alter_receivingreturn_item_dispatchreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchreturn',
            name='delivered_by_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dispatchreturn',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dispatchreturn',
            name='received_by_id',
            field=models.CharField(max_length=50),
        ),
    ]
