# Generated by Django 5.1.1 on 2024-10-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0006_remove_damageoperation_item_remove_dispatch_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='document_number',
            field=models.CharField(max_length=50),
        ),
    ]
