# Generated by Django 5.1.1 on 2024-10-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0007_alter_dispatchreturn_delivered_by_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchreturn',
            name='document_number',
            field=models.CharField(max_length=50),
        ),
    ]
