# Generated by Django 5.1.1 on 2024-10-08 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
        ('Transactions', '0008_alter_dispatchreturn_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_date', models.DateField(default=django.utils.timezone.now)),
                ('document_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('delivered_by_name', models.CharField(max_length=100)),
                ('delivered_by_id', models.CharField(max_length=50)),
                ('received_by_name', models.CharField(max_length=100)),
                ('received_by_id', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='damage_attachments/')),
                ('damaged_quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('item_notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse')),
            ],
        ),
    ]
