# Generated by Django 5.1.1 on 2024-10-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0010_stocktransfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockTransfer',
        ),
    ]
