# Generated by Django 5.1.1 on 2024-10-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0004_item_warehouse'),
        ('Transactions', '0011_delete_stocktransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('paper_number', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_job_number', models.CharField(max_length=50)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_job_number', models.CharField(max_length=50)),
                ('statement', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='Enventory.warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='Enventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_transferred', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.item')),
                ('transfer_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_items', to='Transactions.transferoperation')),
            ],
        ),
    ]
