# Generated by Django 5.1.1 on 2024-10-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0012_transferoperation_transferitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='document_number',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
