# Generated by Django 5.1.1 on 2024-10-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
    ]
