# Generated by Django 5.1.1 on 2024-10-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_receiving_station_remove_receiving_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AddField(
            model_name='station',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AddField(
            model_name='station',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
    ]
