# Generated by Django 5.1.1 on 2024-10-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0002_remove_item_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='item',
        ),
        migrations.RemoveField(
            model_name='station',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='item',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='stockitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
        migrations.AddField(
            model_name='station',
            name='stockitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='stockitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
    ]
