# Generated by Django 5.1.1 on 2024-10-14 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0003_remove_beneficiary_item_remove_station_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='stockitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
    ]
