# Generated by Django 5.1.1 on 2024-10-09 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0003_beneficiary_item_station_item_station_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Enventory.warehouse'),
        ),
    ]
