# Generated by Django 5.1.1 on 2024-10-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0005_alter_supplier_stockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='stockitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='station',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse'),
        ),
    ]
