# Generated by Django 5.1.1 on 2024-10-14 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0007_remove_supplier_stockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='stockitem',
        ),
    ]
