# Generated by Django 5.1.1 on 2024-10-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0009_remove_station_stockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='warehouse',
        ),
    ]
