# Generated by Django 5.1.1 on 2024-10-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0010_remove_station_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Enventory.warehouse'),
        ),
        migrations.AddField(
            model_name='station',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
        migrations.AddField(
            model_name='station',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Enventory.item'),
        ),
    ]
