# Generated by Django 5.1.1 on 2024-10-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0011_beneficiary_item_item_warehouse_station_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity_in_stock',
        ),
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='station',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='item',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='stockitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
        migrations.AddField(
            model_name='station',
            name='stockitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='stockitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Enventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='station',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enventory.warehouse'),
        ),
    ]
