# Generated by Django 5.1.1 on 2024-10-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0012_remove_beneficiary_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='warehouse',
        ),
    ]
