# Generated by Django 5.1.1 on 2024-10-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enventory', '0013_remove_station_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
